### ISSUE TITLE
Add shortcut "Focus Interactive Video Scene Window"

### ISSUE THREAD

**Issue by bhoov** [bhoov/manim-notebook#61] opened 2024-10-30 13:37 UTC
When developing code on a small laptop screen, it is nice to have a full screen of code. But this will hide the preview video. It would be nice to have a hotkey to automatically show the scene that is actively rendering.

Maybe it would be desirable to automatically focus the video screen as soon as a cell or line is executed? This would need to be a setting, because on larger screens or with multiple monitors, you don't want to automatically switch windows.

**Comment by VladimirFokow** [comment] 2024-10-30 19:07
I also had an idea to research:
is it possible to somehow make the video always stay on top?
(even if we click on VSCode)

(Maybe, by modifying something in manimgl?
 ..but I have no idea)

**Comment by VladimirFokow** [comment] 2024-10-30 19:09
to focus a window: MacOS has osascript
(which Grant used to focus back on VSCode, but probably can be adapted to the manim window.. just have to figure out the name of the application)

(I don't know whether other OSs have something like osascript)

**Comment by Splines** [comment] 2024-10-30 21:47
Duplicate of #39

**Closed by Splines** 2024-10-30 21:47 UTC
